using System.Collections.Generic;
using InternalDSL.SemanticModel.Generator;

namespace InternalDSL.SemanticModel
{
    /// <summary>
    /// A description of a test that can contain a number of properties to be
    /// tested by bombarding them with random input generated by an input
    /// generator.
    /// </summary>
    /// <typeparam name="TInput">The type of input given to the properties</typeparam>
    public interface ITest<TInput>
    {
        /// <summary>
        /// A human-readable name of the test, printed in case it is violated.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// The number of random inputs that must be generated.
        /// </summary>
        int Samples { get; }

        /// <summary>
        /// The generator of random inputs.
        /// </summary>
        Generator<TInput> Generator { get; }

        /// <summary>
        /// The properties that must be satisfied for this test to pass.
        /// </summary>
        IList<IProperty<TInput, dynamic>> Properties { get; }
    }

    public class Test<TInput> : ITest<TInput>
    {
        public string Name { get; }
        public int Samples { get; }
        public Generator<TInput> Generator { get; }
        public IList<IProperty<TInput, dynamic>> Properties { get; }

        public Test(string name, int samples, Generator<TInput> generator)
        {
            Name = name;
            Samples = samples;
            Generator = generator;
            Properties = new List<IProperty<TInput, dynamic>>();
        }

        internal void AddProperty(IProperty<TInput, dynamic> property)
        {
            Properties.Add(property);
        }
    }
}
